server:
  shutdown: graceful
  port: 8082
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 1m
    max-connections: 8192
    accept-count: 100
    keep-alive-timeout: 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-collector
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - kafka.yml
      - redis.yml
      - ranking.yml
      - logging.yml
      - monitoring.yml

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd
