### 내 포인트 조회
GET http://localhost:8080/api/v1/users/me/points
X-User-Id: 1

### 포인트 충전
POST http://localhost:8080/api/v1/users/me/points/charge
Content-Type: application/json
X-User-Id: 1

{
  "amount": 10000
}
