pg:
  base-url: http://localhost:8081
  connect-timeout-millis: 3000
  read-timeout-millis: 10000

---
spring:
  config:
    activate:
      on-profile: local, test

pg:
  base-url: http://localhost:8081

---
spring:
  config:
    activate:
      on-profile: dev

pg:
  base-url: http://pg-simulator-dev:8081

---
spring:
  config:
    activate:
      on-profile: qa

pg:
  base-url: http://pg-simulator-qa:8081

---
spring:
  config:
    activate:
      on-profile: prd

pg:
  base-url: http://pg-simulator:8081
